spring:
  application:
    name: gulimall-product
  cloud:
    nacos:
      config:
        server-addr: 10.211.55.8:8848
        namespace: eef8cd02-58de-4978-84fa-2de528bab43f
  config:
    import:
      - optional:nacos:datasource.yml?group=DEVELOP_GROUP
      - optional:nacos:mybatis-plus.yml?group=DEVELOP_GROUP
      - optional:nacos:redis.yml?group=DEVELOP_GROUP
      - nacos:other.yml?group=DEVELOP_GROUP