spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      config:
        server-addr: 10.211.55.8:8848
        namespace: 2debd86a-fce4-4d88-bcff-f5b92659b35e
    gateway:
      routes:
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        - id: thirdparty_route
          uri: lb://gulimall-thirdparty
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*), /$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}

        #nginx负载均衡
        #product服务转发
        - id: gulimall_host_route
          uri: lb://gulimall-product
          predicates:
            - Host=mall.10686.top,item.mall.10686.top
        #search
        - id: search_host_route
          uri: lb://gulimall-search
          predicates:
            - Host=search.mall.10686.top
  config:
    import:
      - nacos:gulimall-gateway.yml?group=DEFAULT_GROUP